# Generated by Django 3.1.5 on 2021-02-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('attendant_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(choices=[('O Positive', 'O Positive'), ('O Negative', 'O Negative'), ('A Positive', 'A Positive'), ('A Negative', 'A Negative'), ('B Positive', 'B Positive'), ('B Negative', 'B Negative'), ('AB Positive', 'AB Positive'), ('AB Negative', 'AB Negative')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'approve'), (2, 'done')])),
                ('the_donors', models.TextField(default='none', max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=30)),
                ('last_donated_date', models.CharField(max_length=30)),
                ('major_illness', models.CharField(max_length=200)),
                ('the_link', models.IntegerField(default=0)),
                ('b_request_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bloodbank.brequests')),
            ],
        ),
    ]
