# Generated by Django 3.1.5 on 2021-02-26 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0002_auto_20210224_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brequests',
            old_name='quantity',
            new_name='blood_quantity',
        ),
        migrations.AddField(
            model_name='contact_us',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
