# Generated by Django 3.1.5 on 2021-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0004_auto_20210322_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brequests',
            name='blood_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
