# Generated by Django 3.1.5 on 2021-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0005_auto_20210322_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brequests',
            old_name='attendantname',
            new_name='attendant_name',
        ),
        migrations.RenameField(
            model_name='brequests',
            old_name='contactnumber',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='brequests',
            name='blood_quantity',
        ),
        migrations.RemoveField(
            model_name='brequests',
            name='state',
        ),
        migrations.RemoveField(
            model_name='brequests',
            name='town',
        ),
        migrations.RemoveField(
            model_name='contact_us',
            name='message',
        ),
        migrations.AddField(
            model_name='brequests',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
