# Generated by Django 3.1.5 on 2021-03-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0007_auto_20210323_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='zipcode',
        ),
    ]
