# Generated by Django 3.1.5 on 2021-03-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0008_remove_donors_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donors',
            name='the_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
