# Generated by Django 3.1.5 on 2021-03-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0009_auto_20210325_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donors',
            name='the_link',
        ),
    ]
