# Generated by Django 3.1.5 on 2021-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0010_remove_donors_the_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
